package kz.offerprocessservice.model.enums;

public enum PriceListStatus {
    NEW, VALIDATION_WAITING, ON_VALIDATION, VALIDATED, VALIDATION_FAILED, PROCESSING, PARTIALLY_PROCESSED, PROCESSED, FAILED
}
