package kz.offerprocessservice.model;

public enum PriceListEvent {

    START_VALIDATION,
    VALIDATION_SUCCESS,
    VALIDATION_ERROR,
    START_PROCESSING,
    PROCESSING_SUCCESS,
    PROCESSING_PARTIALLY_SUCCESS,
    PROCESSING_ERROR
}
