name: basic-pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build the project
        run: |
          ./gradlew build --no-daemon

  test:
    name: Unit-tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: build
    steps:
      - name: Run tests
        run: |
          ./gradlew test --no-daemon